# Generated by Django 4.0 on 2021-12-28 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=70, verbose_name='apellidos')),
                ('dni', models.CharField(max_length=10, verbose_name='cedula identidad')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='dirección')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='correo electrónico')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='fecha nacimiento')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='teléfono')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
        ),
        migrations.CreateModel(
            name='TypePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='tipo persona')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TypeSuscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='tipo suscripción')),
                ('num_days', models.IntegerField(verbose_name='no. días')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='precio')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Suscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suscription', models.DateTimeField(auto_created=True)),
                ('receipt_number', models.CharField(max_length=70, unique=True, verbose_name='no. recibo')),
                ('date_from', models.DateTimeField(verbose_name='fecha desde')),
                ('date_to', models.DateTimeField(verbose_name='fecha hasta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='precio')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='total')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='comentario')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suscriptions.person')),
                ('type_suscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suscriptions.typesuscription')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='type_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suscriptions.typeperson'),
        ),
    ]
