# Generated by Django 4.0 on 2021-12-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesuscription',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='precio'),
        ),
    ]
